### ISSUE TITLE
can't find my profile

### ISSUE THREAD

**Issue by fredguth** [superlumic/superlumic#1]
I created a fredguth.yml file in my superlumic-config git, but I get this message:
No playbook for fredguth found

Can't understand why.

`Fredericos-MBP:usr fredguth$ curl -s https://raw.githubusercontent.com/superlumic/superlumic/master/superlumic | bash -s https://github.com/fredguth/superlumic-config.git
   _________                         .__                .__  
  /   _____/__ ________   ___________|  |  __ __  _____ |**| __**  
  _____  |  |  ____ _/ __ _  __ \  | |  |  \/     |  |/ **_\ 
  /        \  |  /  |_> >  ___/|  | \/  |_|  |  /  Y Y  \  \  \_** 
 /_______  /____/|   **/ _**  >**|  |__**/____/|**|_|  /**|___  >
         \/      |__|        \/ http://superlumic.com \/        \/ 

 --> Checking if we need to ask for a sudo password
 --> Keep-alive: update existing sudo time stamp until we are finished
 --> Install Ansible
/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/private/tmp/pip-build-qmgLsB/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-cu0xH9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-qmgLsB/pycrypto
/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
 --> Create necessary folders
 --> Getting your config from your fork

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

 --> Create ansible.cfg
 --> Get all the required roles
bash: line 130: ansible-galaxy: command not found
 --> No playbook for fredguth found `

**Comment by roderik** [comment]
You installed Xcode and Xcode requires you open it up and accept the licence before you can work with e.g. Git. If you look at your log at the end, it tries to check out your fork. And then fails because it can't use git. So your profile is not there. 

Superlumic installs CLT that also provides git and build tools but doesn't have this issue. ( though in my configure I often need mod_jk that needs a full Xcode to compile )

**Comment by Blacktiger** [comment]
Looks to me like the superlumic script needs some additional error handling built-in for this situation. Since the user already has to enter their password, there is no reason it couldn't re-run the command as sudo if required or at least break out with a more descriptive error message.
